version: '3.3'
services:
  frontend:
    build: .
    container_name: frontend
    ports:
      - '3030:3030'
    command: sh -c "yarn install && yarn build && npm install --global serve && yarn start"
