Create database ql_dean
go

use ql_dean
go

CREATE TABLE PHONGBAN
(
	TENPHG NVARCHAR(50) NOT NULL,
	MAPHG VARCHAR(3) NOT NULL,
	TR_PHG VARCHAR(3) NOT NULL,
	NG_NHANCHUC DATE NOT NULL,
	PRIMARY KEY(MAPHG)
)
GO	

CREATE TABLE NHANVIEN
(
	HONV NVARCHAR(50) NOT NULL,
	TENLOT NVARCHAR(50) NOT NULL,
	TENNV NVARCHAR(50) NOT NULL,
	MANV VARCHAR(3) NOT NULL,
	NGAYSINH DATE NOT NULL,
	DIACHI NVARCHAR(50) NOT NULL,
	PHAI BIT NOT NULL,
	LUONG FLOAT NOT NULL,
	MA_NQL VARCHAR(3) NOT NULL,
	PHG VARCHAR(3)NOT NULL,
	PRIMARY KEY(MANV),
	FOREIGN KEY(PHG) REFERENCES dbo.PHONGBAN(MAPHG)
)
GO	



CREATE TABLE DIADIEM_PHG
(
	MAPHG VARCHAR(3) NOT NULL,
	DIADIEM NVARCHAR(20) NOT NULL,
	PRIMARY KEY(MAPHG,DIADIEM) ,
	FOREIGN KEY (MAPHG) REFERENCES dbo.PHONGBAN(MAPHG),
)
GO	

CREATE TABLE DEAN
(
	TENDA NVARCHAR(20) NOT NULL,
	MADA VARCHAR(3) NOT NULL,
	DDIEM_DA NVARCHAR(20) NOT NULL,
	PHONG VARCHAR(3) NOT NULL,
	PRIMARY KEY(MADA),
	FOREIGN KEY(PHONG) REFERENCES dbo.PHONGBAN(MAPHG)
)
GO	

CREATE TABLE PHANCONG
(
	MANVIEN VARCHAR(3)NOT NULL,
	SODA VARCHAR(3)NOT NULL,
	THOIGIAN FLOAT,
	PRIMARY KEY(SODA,MANVIEN),
	FOREIGN KEY(MANVIEN) REFERENCES dbo.NHANVIEN(MANV),
	FOREIGN KEY(SODA) REFERENCES dbo.DEAN(MADA)

)
GO

CREATE TABLE THANNHAN
(
	MANVIEN VARCHAR(3) NOT NULL,
	TENTN NVARCHAR(20) NOT NULL,
	PHAI BIT NOT NULL,
	NGSINH DATE NOT NULL,
	QUANHE NVARCHAR(15) NOT NULL,
	FOREIGN KEY (MANVIEN) REFERENCES dbo.NHANVIEN(MANV)
)
GO	

-- Thêm Dữ Liệu Bảng Phòng Ban
INSERT dbo.PHONGBAN(TENPHG,MAPHG,TR_PHG,NG_NHANCHUC)VALUES(N'Quản Lý','1',888,'2002-06-19')
INSERT dbo.PHONGBAN(TENPHG,MAPHG,TR_PHG,NG_NHANCHUC)VALUES(N'Điều hành','4',777,'2001-01-01')
INSERT dbo.PHONGBAN(TENPHG,MAPHG,TR_PHG,NG_NHANCHUC)VALUES(N'Nghiên Cứu','5',333,'2005-05-22')
UPDATE dbo.PHONGBAN set TENPHG = N'Nghiên Cứu' WHERE MAPHG=5
-- Thêm Dữ Liệu Bảng Nhân Viên
INSERT dbo.NHANVIEN(HONV,TENLOT,TENNV,MANV,NGAYSINH,DIACHI,PHAI,LUONG,MA_NQL,PHG) VALUES (N'Đinh',N'Bá',N'Tiên',123,'1975-01-09',N'731 Trần Hưng
Đạo Q1 TP.HCM',1,30000,333,5)
INSERT dbo.NHANVIEN(HONV,TENLOT,TENNV,MANV,NGAYSINH,DIACHI,PHAI,LUONG,MA_NQL,PHG) VALUES (N'Nguyễn',N'Thanh',N'Tùng',333,'1975-12-08',N'638 Nguyễn Văn
Cừ Q5 TP.HCM',1,40000,888,5)
INSERT dbo.NHANVIEN(HONV,TENLOT,TENNV,MANV,NGAYSINH,DIACHI,PHAI,LUONG,MA_NQL,PHG) VALUES (N'Trần',N'Thanh',N'Tâm',453,'1982-07-31',N'543 Mai Thi Lựu
Ba Đình Hà Nội',1,25000,333,5)
INSERT dbo.NHANVIEN(HONV,TENLOT,TENNV,MANV,NGAYSINH,DIACHI,PHAI,LUONG,MA_NQL,PHG) VALUES (N'Nguyễn',N'Mạnh',N'Hùng',666,'1982-09-15',N'975 Lê Lai P3
Vũng Tàu',1,38000,333,5)
INSERT dbo.NHANVIEN(HONV,TENLOT,TENNV,MANV,NGAYSINH,DIACHI,PHAI,LUONG,MA_NQL,PHG) VALUES (N'Vương',N'Ngọc',N'Quyền',888,'1977-10-10',N'450 Trưng Vương
Mỹ Tho Tiền Giang',0,55000,0,1)
INSERT dbo.NHANVIEN(HONV,TENLOT,TENNV,MANV,NGAYSINH,DIACHI,PHAI,LUONG,MA_NQL,PHG) VALUES (N'Lê',N'Thị',N'Nhàn','987','1981-06-20',N'291 Hồ Văn Huê
Q.PN TP.HCM',0,43000,888,4)
INSERT dbo.NHANVIEN(HONV,TENLOT,TENNV,MANV,NGAYSINH,DIACHI,PHAI,LUONG,MA_NQL,PHG) VALUES (N'Trần',N'Hồng',N'Quang',777,'1979-03-29',N'980 Lê Hồng
Phong Vũng Tàu',1,25000,987,4)
INSERT dbo.NHANVIEN(HONV,TENLOT,TENNV,MANV,NGAYSINH,DIACHI,PHAI,LUONG,MA_NQL,PHG) VALUES (N'Bùi',N'Thủy',N'Vũ',999,'1978-07-19',N'332 Nguyễn Thái
Học Quy Nhơn',1,25000,987,4)

-- Thêm dữ liệu Bảng Địa Điểm Phòng Ban
INSERT dbo.DIADIEM_PHG(MAPHG,DIADIEM)VALUES('1',N'TP.HCM')
INSERT dbo.DIADIEM_PHG(MAPHG,DIADIEM)VALUES('4',N'HÀ NỘI')
INSERT dbo.DIADIEM_PHG(MAPHG,DIADIEM)VALUES('5',N'NHA TRANG')
INSERT dbo.DIADIEM_PHG(MAPHG,DIADIEM)VALUES('5',N'TP.HCM')
INSERT dbo.DIADIEM_PHG(MAPHG,DIADIEM)VALUES('5',N'VŨNG TÀU')

-- Thêm dữ liệu bảng Dean
insert dbo.DEAN(TENDA,MADA,DDIEM_DA,PHONG) values (N'Sản Phẩm_X','1',N'VŨNG TÀU','5')
insert dbo.DEAN(TENDA,MADA,DDIEM_DA,PHONG) values (N'Sản Phẩm_Y','2',N'Nha Trang','5')
insert dbo.DEAN(TENDA,MADA,DDIEM_DA,PHONG) values (N'Sản Phẩm_Z','3',N'TP.HCM','5')
insert dbo.DEAN(TENDA,MADA,DDIEM_DA,PHONG) values (N'Tin học hóa','10',N'Ha Nội','4')
insert dbo.DEAN(TENDA,MADA,DDIEM_DA,PHONG) values (N'Cáp Quang','20',N'TP.HCM','1')
insert dbo.DEAN(TENDA,MADA,DDIEM_DA,PHONG) values (N'Đào Tạo','30',N'Hà Nội','4')

-- Thêm Dữ liệu vào bảng Phân Công
insert dbo.PHANCONG(MANVIEN,SODA,THOIGIAN) values ('123','1','22.5')
insert dbo.PHANCONG(MANVIEN,SODA,THOIGIAN) values ('123','2','7.5')
insert dbo.PHANCONG(MANVIEN,SODA,THOIGIAN) values ('123','3','10')
insert dbo.PHANCONG(MANVIEN,SODA,THOIGIAN) values ('333','10','10')
insert dbo.PHANCONG(MANVIEN,SODA,THOIGIAN) values ('333','20','10')
insert dbo.PHANCONG(MANVIEN,SODA,THOIGIAN) values ('453','1','20')
insert dbo.PHANCONG(MANVIEN,SODA,THOIGIAN) values ('453','2','20')
insert dbo.PHANCONG(MANVIEN,SODA,THOIGIAN) values ('666','3','40')
insert dbo.PHANCONG(MANVIEN,SODA,THOIGIAN) values ('888','20','0')
insert dbo.PHANCONG(MANVIEN,SODA,THOIGIAN) values ('987','20','15')
insert dbo.PHANCONG(MANVIEN,SODA,THOIGIAN) values ('987','30','20')
insert dbo.PHANCONG(MANVIEN,SODA,THOIGIAN) values ('777','10','35')
insert dbo.PHANCONG(MANVIEN,SODA,THOIGIAN) values ('777','30','5')
insert dbo.PHANCONG(MANVIEN,SODA,THOIGIAN) values ('999','10','10')
insert dbo.PHANCONG(MANVIEN,SODA,THOIGIAN) values ('999','30','30')
-- Thêm dữ liệu bảng nhân than
insert dbo.THANNHAN(MANVIEN,TENTN,PHAI,NGSINH,QUANHE) values ('123',N'Châu',0,'2005-12-31',N'Con Gái') 
insert dbo.THANNHAN(MANVIEN,TENTN,PHAI,NGSINH,QUANHE) values ('123',N'Duy',1,'2001-01-01',N'Con Trai') 
insert dbo.THANNHAN(MANVIEN,TENTN,PHAI,NGSINH,QUANHE) values ('123',N'Phương',0,'1981-05-05',N'Vợ Chồng') 
insert dbo.THANNHAN(MANVIEN,TENTN,PHAI,NGSINH,QUANHE) values ('333',N'Dương',0,'1980-05-03',N'Vợ Chồng') 
insert dbo.THANNHAN(MANVIEN,TENTN,PHAI,NGSINH,QUANHE) values ('333',N'Tùng',1,'2002-10-25',N'Con Trai') 
insert dbo.THANNHAN(MANVIEN,TENTN,PHAI,NGSINH,QUANHE) values ('333',N'Quang',0,'2001-04-05',N'Con Gái') 
insert dbo.THANNHAN(MANVIEN,TENTN,PHAI,NGSINH,QUANHE) values ('987',N'Đăng',1,'1985-02-28',N'Vợ chồng') 


-- Sellect
select * from dbo.NHANVIEN
select *from dbo.DEAN
select *from dbo.DIADIEM_PHG
select *from dbo.PHANCONG
select *from dbo.PHONGBAN
select *from dbo.THANNHAN




----------------------------
--Tạo ràng buộc kiểm tra đảm bảo LUONG của nhân viên chỉ từ 10.000 đến 100.000
ALTER TABLE NHANVIEN ADD CONSTRAINT CHECK_LUONG CHECK (LUONG BETWEEN 10000 AND 100000)
--Tạo ràng buộc kiểm tra đảm bảo THOIGIAN phải không vượt quá 40 (không được làm quá 40 giờ / tuần / đề án )
ALTER TABLE PHANCONG ADD CONSTRAINT KT_THOIGIAN CHECK(THOIGIAN BETWEEN 0 AND 40)

SELECT *FROM PHONGBAN
--SELECT
--Trích ra danh sách nhân viên nam có Lương trên 30.000.
SELECT * FROM NHANVIEN WHERE PHAI = 1 AND LUONG >30000
--Trích ra danh sách nhân viên nữ ở Phòng Nghiên Cứu.
SELECT NV.*,PB.TENPHG FROM NHANVIEN AS NV , PHONGBAN AS PB WHERE NV.PHG = PB.MAPHG AND PB.TENPHG LIKE N'Nghiên Cứu'
--Trích ra danh sách nhân viên nam có tên bắt đầu bằng chữ ‘Q’
SELECT *FROM NHANVIEN WHERE TENNV LIKE 'Q%'
--Trích ra danh sách nhân viên nam từ 30 đến 40 tuổi.
SELECT *FROM NHANVIEN WHERE YEAR(GETDATE())-YEAR(NGAYSINH) >=30 AND YEAR(GETDATE())-YEAR(NGAYSINH)<=40
------------------------------------------------------------------------------------------------------------------------------------------------
SELECT MADA, TENDA, PHONG
FROM PHANCONG, DEAN
WHERE PHANCONG.SODA = DEAN.MADA
GROUP BY MADA, TENDA, PHONG
HAVING count(MANVIEN)>2
--btap 2
SELECT MAPHG, TENPHG, AVG(LUONG) AS 'LƯƠNGTB'
FROM PHONGBAN, NHANVIEN
WHERE PHONGBAN.MAPHG = NHANVIEN.PHG
GROUP BY MAPHG, TENPHG
ORDER BY AVG(LUONG) DESC
--bài tập 3
SELECT MAPHG, TENPHG, AVG(LUONG) AS 'LUONGTB_NAM'
FROM PHONGBAN, NHANVIEN
WHERE PHONGBAN.MAPHG = NHANVIEN.PHG  AND dbo.NHANVIEN.PHAI =1
GROUP BY MAPHG, TENPHG
ORDER BY MAPHG
--BAITAP4
SELECT MAPHG,TENPHG
FROM PHONGBAN, NHANVIEN
WHERE PHONGBAN.MAPHG = NHANVIEN.PHG  AND dbo.NHANVIEN.PHAI = 0
GROUP BY TENPHG,MAPHG
HAVING COUNT(MANV) < 3

--Bài Tập 5
SELECT NV.HONV, NV.TENNV FROM dbo.NHANVIEN AS NV, dbo.THANNHAN AS TN
WHERE nv.MANV = TN.MANVIEN
GROUP BY NV.HONV, NV.TENNV
HAVING COUNT(TN.MANVIEN)>2
--Bài Tập 6
SELECT NV.HONV,NV.TENLOT, NV.TENNV, PB.TENPHG FROM dbo.NHANVIEN AS NV, dbo.THANNHAN AS TN, dbo.PHONGBAN AS PB
WHERE nv.MANV = TN.MANVIEN AND NV.MANV = PB.TR_PHG
GROUP BY NV.HONV,NV.TENLOT, NV.TENNV, PB.TENPHG
HAVING COUNT(TN.MANVIEN)>0

--Bài Tập 7
SELECT NV.TENNV FROM dbo.NHANVIEN AS NV, dbo.PHONGBAN AS PB,dbo.DEAN AS DA,dbo.PHANCONG AS PC
WHERE DA.PHONG = 5 AND NV.MANV = PC.MANVIEN AND DA.MADA = PC.SODA AND PC.THOIGIAN >20 AND DA.TENDA =N'Sản Phẩm_X'
GROUP BY NV.TENNV


--Bài Tập 8
SELECT DA.TENDA, SUM(PC.THOIGIAN) AS N'Tổng Time' FROM dbo.NHANVIEN AS NV, dbo.PHANCONG AS PC, dbo.DEAN AS DA 
WHERE NV.MANV = PC.MANVIEN AND PC.SODA = DA.MADA
GROUP BY DA.TENDA
ORDER BY SUM(PC.THOIGIAN) 
-- Bài Tập 9
SELECT NV.HONV, NV.TENLOT,NV.HONV,PB.TENPHG, NV.LUONG
FROM PHONGBAN AS PB, NHANVIEN AS NV
WHERE PB.MAPHG = NV.PHG AND PB.TENPHG = N'Nghiên Cứu' AND NV.LUONG > (SELECT AVG(nv.LUONG) FROM dbo.NHANVIEN AS nv,dbo.PHONGBAN AS PB WHERE nv.PHG = PB.MAPHG AND PB.TENPHG = N'Nghiên Cứu') 
GROUP BY NV.HONV, NV.TENLOT,NV.HONV,PB.TENPHG,NV.LUONG
ORDER BY AVG(LUONG) 
--Bai Tập 10
SELECT PB.TENPHG, PB.MAPHG,AVG(NV.LUONG) AS N'LUONGTB',COUNT(nv.MANV) AS N'Số Lượng NV' FROM dbo.NHANVIEN AS NV, dbo.PHONGBAN AS PB 
WHERE NV.PHG = PB.MAPHG 
GROUP BY PB.TENPHG, PB.MAPHG
HAVING AVG(NV.LUONG) >=30000
--Bai Tap 11
SELECT NV.TENNV FROM NHANVIEN AS NV
WHERE NV.LUONG >(SELECT (AVG(NV.LUONG)) FROM NHANVIEN AS NV)
--BAI TAP 12
SELECT PB.TENPHG, AVG(YEAR(GETDATE())-YEAR(NV.NGAYSINH)) AS N'TUOI TRUNG BINH' FROM NHANVIEN AS NV, PHONGBAN AS PB 
WHERE PB.MAPHG = NV.PHG
GROUP BY PB.TENPHG

/* TEST
SELECT NHANVIEN.MANV,NHANVIEN.PHG ,(NHANVIEN.HONV + ' ' + NHANVIEN.TENLOT + ' ' + NHANVIEN.TENNV) AS'TÊN NH N VIÊN'
FROM NHANVIEN
WHERE NHANVIEN.LUONG>(SELECT AVG(NHANVIEN.LUONG) FROM NHANVIEN, PHONGBAN 
WHERE NHANVIEN.PHG = PHONGBAN.MAPHG AND PHONGBAN.TENPHG like N'Nghiên cứu')

SELECT * FROM NHANVIEN
SELECT * FROM PHONGBAN

SELECT NV.HONV, NV.TENLOT,NV.TENNV,PB.TENPHG, NV.LUONG
FROM PHONGBAN AS PB, NHANVIEN AS NV
WHERE PB.MAPHG = NV.PHG AND PB.TENPHG = N'Nghiên Cứu' AND NV.LUONG > (SELECT AVG(nv.LUONG) FROM dbo.NHANVIEN AS nv,dbo.PHONGBAN AS PB WHERE nv.PHG = PB.MAPHG AND PB.TENPHG = N'Nghiên Cứu') 
GROUP BY NV.HONV, NV.TENLOT,NV.TENNV,PB.TENPHG,NV.LUONG
ORDER BY AVG(LUONG) 


select distinct MANV, HONV, TENNV
from NHANVIEN, DEAN, PHANCONG
where PHANCONG.THOIGIAN > 20 and DEAN.TENDA like N'Sản Phẩm_X' and DEAN.PHONG = 5
SELECT *FROM PHANCONG, DEAN
WHERE PHANCONG.SODA = DEAN.MADA AND DEAN.TENDA like N'Sản Phẩm_X'
SELECT *FROM DEAN

select distinct MANV, HONV, TENNV
from NHANVIEN, DEAN, PHANCONG
where PHANCONG.THOIGIAN > 20 and DEAN.TENDA like N'Sản Phẩm_X' and DEAN.PHONG = 5
*/
--BT TUAN 7
--CAU 1
SELECT *FROM NHANVIEN AS NV
WHERE NV.MANV NOT IN (
	SELECT MANVIEN FROM PHANCONG
)
-- CAU 2
SELECT  NV.* FROM NHANVIEN AS NV, PHANCONG AS PC 
WHERE NV.MANV = PC.MANVIEN AND PC.SODA IN (
	SELECT SODA FROM PHANCONG AS PC , NHANVIEN AS NV
	WHERE NV.MANV = PC.MANVIEN AND NV.HONV LIKE N'Đinh' and NV.TENLOT LIKE N'Bá' AND NV.TENNV LIKE N'Tiên'
)
--Cau 3
SELECT NV.*FROM NHANVIEN AS NV, PHONGBAN AS PB
WHERE NV.PHG = PB.MAPHG AND PB.TENPHG LIKE N'Nghiên Cứu' AND NV.MANV IN (
    SELECT PHANCONG.MANVIEN FROM PHANCONG
)
--Cau 4
SELECT NV.* FROM NHANVIEN AS NV, DEAN AS DA, PHANCONG AS PC
WHERE DA.DDIEM_DA LIKE N'TP.HCM' AND NV.MANV = PC.MANVIEN AND PC.SODA = DA.MADA AND NV.MANV NOT IN (
	SELECT NV.MANV FROM NHANVIEN AS NV, DIADIEM_PHG AS DD
	WHERE NV.PHG = DD.MAPHG AND DD.DIADIEM LIKE N'TP.HCM'
)
-- Câu 5 
SELECT DISTINCT PB.* FROM PHONGBAN AS PB
WHERE PB.MAPHG NOT IN (
	SELECT PB.MAPHG FROM NHANVIEN as NV, PHONGBAN as PB
	WHERE NV.PHAI = 0 AND NV.PHG  = PB.MAPHG
) 

-- Câu 6 
select PHONGBAN.MAPHG ,PHONGBAN.TENPHONG, count(MANV) as SoLuongNV
from PHONGBAN , NHANVIEN
where NHANVIEN.PHG = PHONGBAN.MAPHG
group by PHONGBAN.MAPHG ,PHONGBAN.TENPHONG
having count(manv) >= all (select count(MANV) from NHANVIEN group by PHG)
--Cau 7
SELECT NV.MANV,(NV.HONV+' '+NV.TENLOT+' '+NV.TENNV) AS N'Tên NV' FROM NHANVIEN AS NV
WHERE NV.MANV NOT in (
	SELECT NV.MANV FROM NHANVIEN AS NV, THANNHAN AS TN
	WHERE NV.MANV = TN.MANVIEN
)
--Cau 8
SELECT DISTINCT NV.TENNV,NV.HONV,PC.MANVIEN FROM NHANVIEN AS NV, DEAN AS DA, PHANCONG AS PC
WHERE NV.MANV = PC.MANVIEN AND DA.MADA = PC.SODA AND PC.SODA NOT IN (	
	SELECT DA.MADA FROM DEAN AS DA WHERE DA.DDIEM_DA LIKE N'Hà Nội'
)


--Bài 8 (Cách 1)
SELECT DISTINCT MANV  ,(HONV+''+TENNV) AS 'HO TEN NHAN VIEN'
FROM NHANVIEN AS NV , PHANCONG AS PC  , DEAN AS DA ,DIADIEM_PHG AS DD
WHERE NV.MANV = PC.MANVIEN AND SODA NOT IN (select MADA from DEAN where DEAN.DDIEM_DA like N'Hà Nội')

-- BÀI 8 (cÁCH 2)
select distinct MANV, (HONV + ' ' + TENNV) as 'ho ten nhan vien'
from NHANVIEN, PHANCONG, DEAN, DIADIEM_PHG
where NHANVIEN.MANV = PHANCONG.MANVIEN
and PHANCONG.SODA = DEAN.MADA
and DEAN.DDIEM_DA not in(N'HÀ NỘI')

--BÀI 9 
select MANV, (HONV + ' ' + TENNV) as 'ho ten nhan vien'
from NHANVIEN, PHANCONG
where NHANVIEN.MANV = PHANCONG.MANVIEN
group by NHANVIEN.MANV, NHANVIEN.HONV, NHANVIEN.TENNV
having COUNT(NHANVIEN.MANV) >= (select COUNT(DEAN.MADA)
from DEAN)

-- BÀI 10 (CÁCH 1)
select (HONV +' '+TENLOT+' ' +TENNV +' ' ) as 'Họ tên'
from NHANVIEN, PHONGBAN
where NHANVIEN.PHG = PHONGBAN.MAPHG and PHG in
(select MAPHG from PHONGBAN, DEAN where PHONGBAN.MAPHG = 5 and DEAN.PHONG =
PHONGBAN.MAPHG)
-- BÀI 10 (CÁCH 2)
select distinct MANV, (HONV + ' ' + TENNV) as 'ho ten nhan vien'
from NHANVIEN, PHONGBAN, DEAN
where NHANVIEN.PHG= PHONGBAN.MAPHG and NHANVIEN.MANV in (
select PHANCONG.MANVIEN
from DEAN, PHANCONG
where DEAN.PHONG=5 and PHANCONG.SODA = DEAN.MADA)

-- BÀI 11
select MANV, (HONV + ' ' + TENNV) as 'ho ten nhan vien'
from NHANVIEN, PHANCONG
where NHANVIEN.MANV=PHANCONG.MANVIEN
group by MANV, HONV, TENNV
having count(PHANCONG.SODA) > 1 and sum(THOIGIAN) > 40